#include "thistle/kernel.h"
#include "thistle/event.h"
#include "thistle/ipc.h"
#include "thistle/driver_manager.h"
#include "thistle/driver_loader.h"
#include "thistle/syscall.h"
#include "thistle/app_manager.h"
#include "thistle/elf_loader.h"
#include "thistle/ota.h"
#include "thistle/permissions.h"
#include "thistle/signing.h"
#include "thistle/net_manager.h"
#include "thistle/wifi_manager.h"
#include "thistle/board_config.h"

#include "esp_log.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

static const char *TAG = "kernel";

static int64_t s_boot_time_us = 0;

esp_err_t kernel_init(void)
{
    s_boot_time_us = esp_timer_get_time();
    ESP_LOGI(TAG, "ThistleOS v" THISTLE_VERSION_STRING " starting");

    esp_err_t ret;

    ESP_LOGI(TAG, "Initializing event bus");
    ret = event_bus_init();
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "event_bus_init failed: %s", esp_err_to_name(ret));
        return ret;
    }

    ESP_LOGI(TAG, "Initializing IPC");
    ret = ipc_init();
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "ipc_init failed: %s", esp_err_to_name(ret));
        return ret;
    }

    ESP_LOGI(TAG, "Initializing network manager");
    ret = net_manager_init();
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "net_manager_init failed: %s", esp_err_to_name(ret));
        return ret;
    }

    ESP_LOGI(TAG, "Initializing syscall table");
    ret = syscall_table_init();
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "syscall_table_init failed: %s", esp_err_to_name(ret));
        return ret;
    }

    /* Board config: reads board.json from SPIFFS, inits buses, loads drivers.
     * Falls back to compiled board_init() + driver_manager if no board.json. */
    ESP_LOGI(TAG, "Initializing board from config");
    ret = board_config_init(NULL);  /* NULL = default /spiffs/config/board.json */
    if (ret != ESP_OK) {
        ESP_LOGW(TAG, "board_config_init failed: %s — trying compiled board_init()",
                 esp_err_to_name(ret));
        /* Fallback: use the old compiled-in driver path */
        driver_manager_init();
        driver_manager_start_all();
        driver_loader_init();
        driver_loader_scan_and_load();
    }

    ESP_LOGI(TAG, "Initializing app manager");
    ret = app_manager_init();
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "app_manager_init failed: %s", esp_err_to_name(ret));
        return ret;
    }

    ESP_LOGI(TAG, "Initializing permissions subsystem");
    ret = permissions_init();
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "permissions_init failed: %s", esp_err_to_name(ret));
        return ret;
    }

    ESP_LOGI(TAG, "Initializing signing subsystem (Ed25519)");
    /* Dev Ed25519 public key — generated by tools/sign.py keygen
     * Replace with production key for release builds. */
    static const uint8_t dev_signing_key[32] = {
        0x25, 0xd3, 0xfc, 0xbc, 0x28, 0x2d, 0xb4, 0x6f,
        0xf4, 0x37, 0x78, 0x5c, 0x32, 0x90, 0xaf, 0x73,
        0x98, 0x17, 0xf2, 0x0d, 0xb4, 0x37, 0x88, 0x27,
        0xf9, 0x00, 0xc3, 0xf7, 0x7b, 0xe0, 0x27, 0xb7,
    };
    ret = signing_init(dev_signing_key);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "signing_init failed: %s", esp_err_to_name(ret));
        return ret;
    }

    ESP_LOGI(TAG, "Initializing ELF loader");
    ret = elf_loader_init();
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "elf_loader_init failed: %s", esp_err_to_name(ret));
        return ret;
    }

    ESP_LOGI(TAG, "Initializing OTA subsystem");
    ret = ota_init();
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "ota_init failed: %s", esp_err_to_name(ret));
        return ret;
    }

    /* Initialize WiFi and register it as a network transport.
     * Done after OTA init so the full subsystem is ready.
     * Non-fatal if WiFi is unavailable (e.g. cellular-only board). */
    ret = wifi_manager_init();
    if (ret != ESP_OK) {
        ESP_LOGW(TAG, "wifi_manager_init failed: %s — WiFi transport unavailable",
                 esp_err_to_name(ret));
    } else {
        net_manager_register_wifi();
    }

    ESP_LOGI(TAG, "Publishing SYSTEM_BOOT event");
    ret = event_publish_simple(EVENT_SYSTEM_BOOT);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Failed to publish SYSTEM_BOOT: %s", esp_err_to_name(ret));
        /* Non-fatal — continue */
    }

    ESP_LOGI(TAG, "Kernel init complete (uptime: %" PRIu32 " ms)", kernel_uptime_ms());
    return ESP_OK;
}

void kernel_run(void)
{
    ESP_LOGI(TAG, "Entering kernel main loop");

    /* The LVGL tick and render are driven by the UI component.
     * This loop is the kernel heartbeat — it keeps the idle task
     * alive and provides a hook for future watchdog / power management. */
    for (;;) {
        vTaskDelay(pdMS_TO_TICKS(10));
    }
}

uint32_t kernel_uptime_ms(void)
{
    return (uint32_t)((esp_timer_get_time() - s_boot_time_us) / 1000);
}
